notifications:
  email: false
sudo: required
language: ruby
rvm:
  - 2.5.5
bundler_args: --without development:production
cache:
  bundler: true
env:
  - RAILS_ENV=test
services:
  - docker
before_script:
  - bundle exec ./docker/setup
  - docker-compose up -d
  - bundle exec rake db:mongoid:create_indexes
  - bundle exec rake db:seed
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - bundle exec rspec
after_script:
  - ./cc-test-reporter after-build -t simplecov --exit-code $TRAVIS_TEST_RESULT
addons:
  firefox: latest
